.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "UMQ\-RECV" "1" "December 2013" "" ""
.
.SH "NAME"
\fBumq-recv\fR \-\- tcp/udp listen transport utility
.
.SH "SYNOPSIS"
\fBumq\-recv <host> <port>\fR [\-hvV] [\-f <file>]
.
.SH "OPTIONS"
  \fB\-f, \-\-file\fR <file>       file to execute on each chunk received
  \fB\-v, \-\-verbose\fR           show verbose output
  \fB\-h, \-\-help\fR              display this message
  \fB\-V, \-\-version\fR           output version
.
.SH "USAGE"
\fB
$ umq push localhost 3000\fR
.
.SH "AUTHOR"
.
.IP "\(bu" 4
Joseph Werle \fIjoseph\.werle@gmail\.com\fR
.
.IP "" 0
.
.SH "REPORTING BUGS"
.
.IP "\(bu" 4
https://github\.com/jwerle/umq/issues
.
.IP "" 0
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
https://github\.com/jwerle/umq
.
.IP "" 0
.
.SH "LICENSE"
  MIT (C) Copyright Joseph Werle 2013